#!/usr/bin/env python

Import("env")
Import("env_modules")

env_ai = env_modules.Clone()

module_obj = []
env_ai.add_source_files(module_obj, "*.cpp")
env_ai.add_source_files(module_obj, "resources/*.cpp")

if env.editor_build:
    env_ai.add_source_files(module_obj, "editor/*.cpp")

env.modules_sources += module_obj
